### PR TITLE
Adding enterprises working on ethereum

### LINKED ISSUE #299: [Bounty] Gather Ethereum Enterprise Resources
## Requirement

List all the companies/enterprises building on top of Ethereum on this [page](https://github.com/ethhub-io/ethhub/blob/master/docs/built-on-ethereum/enterprise/enterprise.md).

## Gather resources for companies:
- Building on public or private Ethereum
- Working on enterprise use-cases (such as EY's Nightfall or JPMs Zether)
- Integrating Ethereum-based products into their own apps in some way (such as Google integrating Chainlink).

## Resources to get you started:
- https://entethalliance.org/
- https://consensys.net/enterprise-ethereum/

### PR DESCRIPTION
**Pull request by nanspro**
Fixes #299 

- [x] Building on public or private Ethereum
- [x] Working on enterprise use-cases
- [x] Integrating Ethereum-based products into their own apps in some way.
- [x] Added enterprise projects case studies

### CODE REVIEW

**Comment by sassal** [comment]
Great work so far!

Are you able to add more things from ConsenSys? It can be anything enterprise-related as long as it has to do with Ethereum (such as their Pantheon client).

It would be great to also add companies that are using "EVM based chains" such as Axoni and DTCC!

**Comment by nanspro** [comment]
@sassal i assumed you wanted large companies outside of ethereum community who are building on it, if that's not the case then can i add startups using ethereum who are working on enterprise based solutions like pegasys-pantheon ?

Also does it make sense to add projects like IBM:fabric, Intel:Sawtooth, which are built separately (not on ethereum) but provide support for ethereum smart contracts.

**Comment by sassal** [comment]
Yeah I think having everything listed that touches Ethereum in some way would be best - I should of been more clear in the original post - apologies!

**Comment by nanspro** [comment]
@sassal check it out now :)

**Pull request merged**
