### PR TITLE
fix: add link to interacting with clients

### PR DESCRIPTION
**Pull request by BelfordZ**

### CODE REVIEW

**Comment by BelfordZ** [comment]
@sassal Thanks for your hard work on this.

I was hoping you could help me understand why there is no link to the doc? Am I missing a step?

Thanks in advance.

**Comment by sassal** [comment]
Oversight - thanks for picking it up :)

**Comment by sassal** [comment]
Fixed - the latest build hadn't been pushed out to mkdocs on our end :)

**Comment by BelfordZ** [comment]
Thank you good sir

**Pull request merged**
