### PR TITLE
adding Cryptact under resources.

### PR DESCRIPTION
**Pull request by smasuda**
Cryptact is offering crypto-tax calculation as well as portfolio tracking tool. The tax calculation tool is the largest in this kind in Japan,  while it offers support in English as well.

### CODE REVIEW

**Comment by sassal** [comment]
Hey! Thanks for adding that one but unfortunately we were actually meant to remove the 'Crypto Accounting Tools' section (it somehow made it through testing).

**Comment by smasuda** [comment]
I see, thanks!
Do you plan to keep 'Portfolio Tracking' section? If so I'd like to try the one.

**Comment by sassal** [comment]
It depends what it is really. We don't want any of the pages on the site to be used as an advertisement for products/services but we also want to provide as many helpful resources as possible. I can review it if you post it here :)

**Comment by smasuda** [comment]
@sassal  thanks for the clarification. Also, I understand your points.
I don't hide my intention being partially inclined to the ad in this comprehensive resource page; at the  same time the service is free for non-commercial use at the moment and we are confident that what we offer would help majority of people who seek this kind of solution. I'd raise another PR with more background information for you to judge.

**Pull request closed without merging**
