### PR TITLE
Update ethhub-cftc-response.md

### PR DESCRIPTION
**Pull request by charlie-wiser**
This edit adds Tezos, the first large-scale PoS/LPoS blockchain to launch, to the "Has a proof of stake consensus mechanism been tested or validated at scale? If so, what lessons or insights can be learned from the experience?" section.

### CODE REVIEW

**Comment by econoar** [comment]
Not sure I see the relevance of putting Tezos in this document.

**Comment by charlie-wiser** [comment]
I would agree if there were not the question of "Has a proof of stake consensus mechanism been tested or validated at scale? If so, what lessons or insights can be learned from the experience?" Given the inclusion of this question, I think that mentioning Tezos is reasonable and particularly relevant.

**Comment by econoar** [comment]
Tested at scale is a stretch IMO. I think it's best to remove all project names other than Ethereum and Bitcoin. That way this document doesn't turn into a "look at this" project as that's not the point. Will leave this open for now as the document evolves.

**Comment by charlie-wiser** [comment]
That makes sense. I suggest removing Peercoin and NXT in that case.

**Comment by econoar** [comment]
Agreed, I will do that instead.

**Pull request closed without merging**
